apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: authentication-policy
  namespace: census
spec:
  selector:
    matchLabels:
      app: spring-census
  jwtRules:
  - issuer: "https://dev-n8xq5t40atbepes2.us.auth0.com/"
    jwksUri: "https://dev-n8xq5t40atbepes2.us.auth0.com/.well-known/jwks.json"
    